name: build

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1 # checkout latest commit
    - name: Use Node.js ${{ matrix.node-version }} # set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies # runs the npm ci command to install all dependencies
      run: |
        npm ci
      env:
        CI: "true"
    - name: Lint Script # runs ESLint to check the code for broken conventions
      run: |
        npm run lint
      env:
        CI: "true"
    - name: Build App # builds the Electron app for Linux and MacOS
      run: |
        npm run build-unix
      env:
        CI: "true"
